sudo: true
services:
  - docker

language: python
python:
  - "3.5"

branches:
  only:
    - master

env:
  global:
    - NEOMAKE_DOCKER_IMAGE: neomake/vims-for-tests:4@sha256:8ca565fa0c8c0c3ae40b3f705c05a084e260b07022559fc56636c3675321c38b
  matrix:
    - ENV=vimlint
    - ENV=docker_test MAKE_ARGS=DOCKER_VIM=neovim-v0.2.0
    - ENV=docker_test MAKE_ARGS=DOCKER_VIM=neovim-v0.1.7
    - ENV=docker_test MAKE_ARGS=DOCKER_VIM=vim-master
    - ENV=docker_test MAKE_ARGS=DOCKER_VIM=vim8069
    - ENV=docker_test MAKE_ARGS=DOCKER_VIM=vim74-xenial
    - ENV=docker_test MAKE_ARGS=DOCKER_VIM=vim73
    # Same as neovim-v0.2.0 and the bot-ci script is broken currently, so skip it for now.
    # - ENV=testnvim
    - ENV=testvim
    - ENV=check
    - ENV=vint

matrix:
  fast_finish: true

install:
  - |
    if [ "$ENV" = "check" ]; then
      echo "Looking for changed files in $TRAVIS_COMMIT_RANGE."
      if ! git diff --exit-code --quiet "$TRAVIS_COMMIT_RANGE" doc/neomake.txt; then
        MAKE_ARGS="$MAKE_ARGS docker_vimhelplint"
        echo 'doc/neomake.txt changed, running docker_vimhelplint'
      fi
    elif [ "$ENV" = "testnvim" ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"

      # Install vim-vimhelplint for one build.
      make build/vimhelplint
    fi

    python3 -V
    python2 -V

script:
  - |
    if [[ "$ENV" = "testvim" ]]; then
      vim --version
      if ! vim --version 2>&1 | grep -F 'VIM - Vi IMproved 7.4' -A1 | grep -q '^Included patches: 1-52'; then
        echo 'Unexpected Vim version (expected 7.4.52)' >&2
        exit 1
      fi
    fi
    umask 022
    echo "===== running: make $ENV $MAKE_ARGS ====="
    make $ENV $MAKE_ARGS
